# Generated by Django 4.1.7 on 2023-03-10 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_App', models.CharField(max_length=30)),
                ('Cantidad_Comentarios', models.IntegerField()),
                ('positive_comments', models.IntegerField()),
                ('neutral_comments', models.IntegerField()),
                ('negative_comments', models.IntegerField()),
                ('emotion_comments', models.CharField(max_length=30)),
                ('date_consulted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_consulted'],
            },
        ),
    ]
