# Generated by Django 4.1.7 on 2023-03-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={},
        ),
    ]
